const players = [
  { id: "P001", name: "Virat Kohli", category: "Batter", team: "IND", group: "A", credits: 10 },
  { id: "P002", name: "Rohit Sharma", category: "Batter", team: "IND", group: "A", credits: 9 },
  { id: "P003", name: "Jasprit Bumrah", category: "Bowler", team: "IND", group: "A", credits: 9 },
  { id: "P004", name: "Hardik Pandya", category: "All-Rounder", team: "IND", group: "A", credits: 9.5 },
  { id: "P005", name: "MS Dhoni", category: "Wicket-Keeper", team: "IND", group: "A", credits: 8 },
  { id: "P006", name: "Ben Stokes", category: "All-Rounder", team: "ENG", group: "B", credits: 10 },
  { id: "P007", name: "Jos Buttler", category: "Wicket-Keeper", team: "ENG", group: "B", credits: 9 },
  { id: "P008", name: "Jofra Archer", category: "Bowler", team: "ENG", group: "B", credits: 9 },
  { id: "P009", name: "Jonny Bairstow", category: "Batter", team: "ENG", group: "B", credits: 9 },
  { id: "P010", name: "Joe Root", category: "Batter", team: "ENG", group: "B", credits: 9.5 },
  { id: "P011", name: "Babar Azam", category: "Batter", team: "PAK", group: "C", credits: 10 },
  { id: "P012", name: "Shaheen Afridi", category: "Bowler", team: "PAK", group: "C", credits: 9 },
  { id: "P013", name: "Shadab Khan", category: "All-Rounder", team: "PAK", group: "C", credits: 9 },
  { id: "P014", name: "Mohammad Rizwan", category: "Wicket-Keeper", team: "PAK", group: "C", credits: 8.5 },
  { id: "P015", name: "Fakhar Zaman", category: "Batter", team: "PAK", group: "C", credits: 9 },
  { id: "P016", name: "David Warner", category: "Batter", team: "AUS", group: "D", credits: 9.5 },
  { id: "P017", name: "Pat Cummins", category: "Bowler", team: "AUS", group: "D", credits: 10 },
  { id: "P018", name: "Glenn Maxwell", category: "All-Rounder", team: "AUS", group: "D", credits: 9.5 },
  { id: "P019", name: "Matthew Wade", category: "Wicket-Keeper", team: "AUS", group: "D", credits: 8.5 },
  { id: "P020", name: "Steve Smith", category: "Batter", team: "AUS", group: "D", credits: 9 }
];
